name: C++ CI com cobertura

on:
  push:
    branches: [ worflow_teste_03 ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Instalar dependências
      run: |
        sudo apt-get update
        sudo apt-get install -y gcovr lcov g++ cmake

    - name: Configurar CMake com cobertura
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON

    - name: Compilar
      run: cmake --build build

    - name: Executar testes
      run: ctest --test-dir build --output-on-failure

    - name: Gerar cobertura HTML e XML
      run: |
        cmake --build build --target coverage
      

    - name: Upload de relatórios
      uses: actions/upload-artifact@v4
      with:
        name: cobertura
        path: build/coverage*
