name: C++ CI com cobertura

on:
  push:
    branches: [ workflow_teste_02 ]


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Instalar gcovr
      run: sudo apt-get update && sudo apt-get install -y gcovr

    - name: Configurar CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build build

    - name: Rodar testes
      run: ctest --test-dir build --output-on-failure

    - name: Gerar cobertura via alvo do CMake
      run: cmake --build build --target coverage

    - name: Upload dos relatórios de cobertura como artefato
      uses: actions/upload-artifact@v4
      with:
        name: cobertura-gcovr
        path: |
          build/coverage.html
          build/coverage.xml
